jobs:
  build:
    if: github.repository_owner == 'mybatis' && ! contains(toJSON(github.event.head_commit.message),
      '[maven-release-plugin]')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      uses: webfactory/ssh-agent@master
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - continue-on-error: true
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build site
      run: ./mvnw site site:stage -DskipTests -B -V --no-transfer-progress -Dlicense.skip=true
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Deploy Site to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.6.1
      with:
        branch: gh-pages
        folder: target/spring-boot-starter.git
        ssh-key: true
name: Site
on:
  repository_dispatch:
    types: trigger-ga___site.yaml
