jobs:
  build:
    if: github.repository_owner == 'mybatis' && ! contains(toJSON(github.event.head_commit.message),
      '[maven-release-plugin]')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      env:
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      name: Deploy to Sonatype
      run: ./mvnw deploy -DskipTests -B -V --no-transfer-progress --settings ./.mvn/settings.xml
        -Dlicense.skip=true
name: Sonatype
on:
  repository_dispatch:
    types: trigger-ga___sonatype.yaml
