jobs:
  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test with Spring Boot Latest
      run: './mvnw package

        ./mybatis-spring-boot-samples/run_fatjars.sh

        '
    strategy:
      fail-fast: false
      matrix:
        distribution:
        - zulu
        java:
        - 17
        - 21
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
      max-parallel: 5
name: Spring Boot Support Samples
on:
  repository_dispatch:
    types: trigger-ga___support.yaml
